import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './fixtures.mjs';
test('carrinho persiste sabores e kits, usa desconto no WhatsApp e permite remover inativos', async (t) => {
  let stored = JSON.stringify([{ productId: 'morango', quantity: 1 }]);
  globalThis.localStorage = { getItem: () => stored, setItem: (_key, value) => { stored = value; } };
  globalThis.location = { hostname: 'localhost' };
  let items = fixture();
  t.mock.method(globalThis, 'fetch', async () => Response.json({ items }));
  const { loadCatalog, apiUrl } = await import('../js/products.js');
  assert.equal(apiUrl('/api/catalog'), '/api/catalog');
  const cart = await import('../js/cart.js');
  const { buildWhatsAppMessage, buildWhatsAppUrl } = await import('../js/whatsapp.js');
  await loadCatalog();
  assert.equal(cart.getCartItemCount(), 1);
  assert.equal(cart.addToCart('cone', 1, 'ninho'), true);
  assert.equal(cart.addToCart('kit', 2), true);
  assert.equal(cart.getCartTotal(), 63);
  assert.equal(cart.addToCart('cone', 1, 'ninho'), false);
  assert.match(cart.getLastCartError(), /Estoque/);
  const message = buildWhatsAppMessage('Retirada às 15h');
  assert.match(message, /Cone trufado — Ninho/);
  assert.match(message, /Composição de cada kit/);
  assert.match(message, /63,00/);
  assert.match(message, /Retirada às 15h/);
  assert.match(buildWhatsAppUrl(), /^https:\/\/wa.me\/5519971107606\?text=/);
  assert.equal(JSON.parse(stored).find((line) => line.productId === 'cone').variantId, 'ninho');
  items[1].active = false;
  await loadCatalog();
  assert.match(cart.getCartError(), /inativado/);
  assert.equal(cart.getDetailedCartItems().find((line) => line.productId === 'cone').unavailable, true);
  assert.equal(cart.removeFromCart('cone:ninho'), true);
  assert.equal(cart.removeFromCart('kit'), true);
  assert.equal(cart.getCartError(), '');
  cart.clearCart();
  assert.equal(cart.isCartEmpty(), true);
  assert.equal(buildWhatsAppUrl(), null);
});
